language: node_js

env:
  global:
  # RIA_PACKAGER_TIMESTAMP_URL=http://sha256timestamp.ws.symantec.com/sha256/timestamp
  - RIA_PACKAGER_TIMESTAMP_URL=http://timestamp.digicert.com/
  - SHOCKPKG_PACKAGES_AIR_1_2="
      air-sdk-1.0.7.4880-mac-zip
      air-sdk-1.0.7.4880-windows
      air-sdk-1.1.0.5790-mac-zip
      air-sdk-1.1.0.5790-windows
      air-sdk-1.5.0.7220-mac-zip
      air-sdk-1.5.0.7220-windows
      air-sdk-1.5.3.9120-mac-zip
      air-sdk-1.5.3.9120-windows
      air-sdk-2.0.1.12090-mac-zip
      air-sdk-2.0.1.12090-windows
      air-sdk-2.7.1.19610-mac-zip
      air-sdk-2.7.1.19610-windows"
  - SHOCKPKG_PACKAGES_AIR_3="
      air-sdk-3.0.0.4080-mac-zip
      air-sdk-3.0.0.4080-windows
      air-sdk-3.2.0.2070-mac-zip
      air-sdk-3.2.0.2070-windows
      air-sdk-3.6.0.6090-mac-zip
      air-sdk-3.6.0.6090-windows"
  - SHOCKPKG_PACKAGES_AIR_25="
      air-sdk-25.0.0.134-mac-zip
      air-sdk-25.0.0.134-windows"
  - SHOCKPKG_PACKAGES_AIR_27="
      air-sdk-27.0.0.128-mac-zip
      air-sdk-27.0.0.132-windows"
  - SHOCKPKG_PACKAGES_AIR_32="
      air-sdk-32.0.0.116-mac-zip
      air-sdk-32.0.0.116-windows"
  - SHOCKPKG_PACKAGES_AIR_33="
      air-sdk-33.0.2.330-mac
      air-sdk-33.0.2.330-windows
      air-sdk-33.1.1.259-mac
      air-sdk-33.1.1.259-windows"

matrix:
  include:
  - os: linux
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_1_2"

  - os: osx
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_1_2"

  - os: windows
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_1_2"

  - os: linux
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_3"

  - os: osx
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_3"

  - os: windows
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_3"

  - os: linux
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_32"

  - os: osx
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_32"

  - os: windows
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_32"

  - os: linux
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_33"

  - os: osx
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_33"

  - os: windows
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_33"

  - os: linux
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_1_2"

  - os: osx
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_1_2"

  - os: windows
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_1_2"

  - os: linux
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_3"

  - os: osx
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_3"

  - os: windows
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_3"

  - os: linux
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_25"

  - os: osx
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_25"

  - os: windows
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_25"

  - os: linux
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_27"

  - os: osx
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_27"

  - os: windows
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_27"

  - os: linux
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_32"

  - os: osx
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_32"

  - os: windows
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_32"

  - os: linux
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_33"

  - os: osx
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_33"

  - os: windows
    node_js: v14.11.0
    env:
    - SHOCKPKG_PACKAGES="$SHOCKPKG_PACKAGES_AIR_33"

script:
- npm run shockpkg -- update --summary
- npm run shockpkg -- install $SHOCKPKG_PACKAGES
- npm run clean
- if [ "$NO_LINT" != "1" ]; then npm run lint; fi
- npm run build
- npm run test
